version: '3.8'

services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web_api
    networks:
      - webnet

  web_api:
    environment:
      - PING_LISTEN_PORT=3000
    build:
      context: .
      dockerfile: Dockerfile
    image: tp3_image
    deploy:
      replicas: 4
    networks:
      - webnet

networks:
  webnet:
